name = "payroll-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = true

[vars]

[secrets]
required = [ "JWT_SECRET", "GOOGLE_CLIENT_ID", "GMAIL_CLIENT_SECRET" ]

# Serve the frontend SPA from the worker
[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "payroll_db"
database_id = "f83d9b4b-97e3-4c91-92b7-08709320e8d0"
migrations_dir = "migrations"

[dev]
port = 5001
